remix-run/indie-stack

app/routes/notes/new.tsx

Super minor - noticed a double space in the class name while playing around.

Remove double space in class name

---

.github/workflows/deploy.yml

Currently Cypress task for the deploy Github Action runs them in a row:
* `npx prisma migrate reset --force`
* `npx prisma db seed`
Because [`prisma migrate reset` also runs seed command](https://www.prisma.io/docs/concepts/components/prisma-migrate#reset-the-development-database), it could fail if the seed script inserts with unique keys specified for example:
We should remove explicit `npx prisma db seed` there so seed runs only once.

fix: Make seeding happen only once for Cypress in Github Actions

---

app/routes/healthcheck.tsx

Reduces the chances for internal services to be affected by sending a malicious `Host` header to the health check route

fix: omit path and query string from healthcheck route

---

app/entry.client.tsx

i just saw that the indie-stack has react 18.0.0 but the entry.client was using old hydrate. Not sure if this was on purpose but on discord I was told to send a PR nonetheless.
I looked at server.entry and thought of adding `renderToReadableStream` but I think this might have more implications than I understand about remix's choices.

fix: entry.client not using the new hydrateRoot

---

.github/workflows/deploy.yml

A new repository I started from this template had default permissions for `GITHUB_TOKEN` set to "contents:read" and "metadata:read". I think this has changed recently because I use to be able to get actions running before April. I think it used to be read/write by default and now it's read:
My workflow execution failed because styfle/cancel-workflow-action needs "actions:write" permissions (my guess is so that it can [cancel a run](https://docs.github.com/en/rest/actions/workflow-runs#cancel-a-workflow-run) or something like that).
Adding "contents:read" and "actions:write" explicitly in the workflow file made this work.

Add explicit github workflow permissions

---

app/session.server.ts

Setting maxAge: 0 will automatically expire the cookie as soon as it's sent. This should not be the default value. Otherwise, the developer will have to override this on every set-cookie header. Leaving it undefined ensures the cookie will live for the life of the browser session.
See https://github.com/remix-run/blues-stack/pull/85

fix: remove maxAge from session cookie

---

package.json

we ship a migration, thus not generating one so we can use deploy instead of dev which also fixes the double seeding

chore: use `prisma migrate deploy`

---

package.json

resolves an issue when a precompiled Prisma engine doesn't exist for an OS
closes #88

chore: run `prisma generate` manually during setup

---

README.md

there's been a few PRs/issues across the official stacks about missing .env files and i haven't heard back whether or not these folks have opted out of the CLI installing deps for them to be certain, but perhaps we add an explicit step about it just in case
resolves #111
resolves #54

chore: add note about running remix init if you skip installing deps

---

app/routes/index.tsx

the classname `.lg:pb-18` doesn't exist in tailwind's default spacing scale. hint: why it was being ordered before `.relative`
this replaces it with `.lg:pb-20`

fix: replace `.lg:pb-18` with a valid classname

---

README.md

With the new Fly CLI you will get this error if you try to do `fly create xxx`:
```
Command "create" is deprecated, replaced by 'apps create'
```
The new way of creating an app is: `fly apps create xxx`.

Update fly app creation command

---

.github/workflows/deploy.yml
cypress/support/create-user.ts
cypress/support/delete-user.ts
package.json
prisma/seed.ts
remix.init/index.js
remix.init/package.json
vitest.config.ts

---
https://github.com/remix-run/remix/pull/3150 needs to be merged first
Closes #61

feat: remove all TypeScript references when `isTypeScript` is passed as `false` to `remix.init`

---

.eslintrc.js
cypress/support/commands.ts
package.json
remix.init/index.js

Part of the solution is also a change in the transform, which is implemented in https://github.com/remix-run/remix/pull/3987
---
This will partially resolve #134
Closes #136
Closes #139
Closes #140

fix: fix `remix.init`

---

remix.init/index.js

Missed this when implementing #128 🙈
---
Closes #143

chore: fix file paths in `remix.init`

---

.github/dependabot.yml
remix.init/index.js

It's hard to know if GitHub Actions have a new version
I could have enabled it for normal dependencies as well, but I know @kentcdodds isn't a big fan of it + we don't have a lockfile, so it would only create PRs for major releases

chore: enable Dependabot for GitHub Actions

---

app/routes/index.tsx

Set the `object-fit` CSS property to `contain`, to **make sure logos with different aspect ratios will not be stretched** and shown properly. This stretching happens when a new logo is added to the technologies array with a different aspect ratio like 4:1. Now it's fixed.

fix(ui): use object-contains for logos

---

package.json

Fixes an issue with MSW (
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib' is not defined by "exports" in /node_modules/headers-polyfill/package.json)
MSW recent release [0.47.3](https://github.com/mswjs/msw/pull/1407) fixes the issue.

fix: update `msw`

---

README.md

x-ref https://github.com/remix-run/blues-stack/pull/135
seems like `http://gitpod.io/from-referrer/` no longer works

chore: update gitpod url

---

package.json

Apparently we need to add the `-p` flag when running `tsc` on the `cypress` folder
https://github.com/remix-run/indie-stack/actions/runs/3951228293/jobs/6764810424

fix: fix `typecheck` script

---

.github/workflows/deploy.yml

A recent change to the build-runner breaks deployment.
https://community.fly.io/t/deploying-to-fly-via-github-action-failing/10171/19

fix: Update docker build step to use older builder

---

start.sh

Just like @kwigley's https://github.com/remix-run/blues-stack/pull/183
Fixes #200

fix: add swapfile

---

app/db.server.ts
app/singleton.server.ts

Should have been in #243 as well 🙈
Thanks @jenseng for this awesome utility! 🙏

feat: simplify Prisma setup

---

cypress/support/commands.ts
cypress/support/create-user.ts
cypress/support/delete-user.ts
package.json
remix.init/index.js

feat: optimize commands for Bun

---

package.json
prettier.config.js

This PR changes the `prettier.config.js` export type to CommonJS to fix the currently failing project creation from this template.
Without this change, prettier is unable to parse the `prettier.config.js` file ([more context](https://prettier.io/blog/2023/07/05/3.0.0.html#support-config-files-in-esm-13130httpsgithubcomprettierprettierpull13130-by-fiskerhttpsgithubcomfisker)) and so the project creation from this template fails.
Fixes https://github.com/remix-run/indie-stack/issues/294

Fix failing project creation from this template
