- package-lock.json
- package.json
> chore: update `package-lock.json`

- package.json
> fix: eslint cache

- app/models/note.server.ts
- app/models/user.server.ts
Inspired by @joematune's PR in the Grunge stack (https://github.com/remix-run/grunge-stack/pull/22)
> feat: make models more type-safe

- README.md
- package.json
- remix.init/index.js
Similar to the changes in https://github.com/remix-run/blues-stack/pull/29, plus temporarily removing the initial question for the validate script until we can figure out the Cypress issue (at least on my machine 🙃)
> README updates and init script tweaks

- app/routes/login.tsx
> Use current password instead of new password for login page

- README.md
> docs: fix 1Password password generator URL

- app/session.server.ts
Just like @Code42Cate did in https://github.com/remix-run/blues-stack/pull/46
> chore: remove explicit return types

- remix.config.js
Follow-up of https://github.com/remix-run/remix/pull/2739 & https://github.com/remix-run/remix/pull/2869
> chore: ignore dotfiles in route subdirectories too

- .eslintrc.js
> chore: add missing word to eslintrc comment

- cypress/support/create-user.ts
> fix(cypress): use a real url when making a request

- Dockerfile
> chore: only copy minimal set of files when building final image

- fly.toml
Just like https://github.com/remix-run/blues-stack/pull/68
> fix: fix invalid `fly.toml`

- package.json
- prisma/seed.js
Signed-off-by: Logan McAnsh <logan@mcan.sh>
> chore: convert seed script to cjs

- .npmrc
- Dockerfile
> chore: add npmrc with legacy-peer-deps

- cypress/e2e/smoke.cy.ts
- cypress/support/commands.ts
Currently the cypress suites fail constantly because of Cypress and React Hydrating the document. 
Issue: https://github.com/remix-run/indie-stack/issues/130
After looking through some of the cypress issues I came across this comment.
https://github.com/cypress-io/cypress/issues/7306#issuecomment-1152752612
It talks about adding a new cypress command which checks too makes sure that the url you are visiting matches the pathname.
Its not the best but since adding it in I have ran the cypress suite a dozen times with no fails
> added a checkUrl function to make sure that the DOM has been mounted

- cypress/support/delete-user.ts
Just like @raytiley did in remix-run/blues-stack#108
> fix(Cypress): fix `delete-user` command on Windows

- README.md
> docs: update docs link

- package.json
- tailwind.config.js
- tailwind.config.ts
[ESM & TS support is now officially released](https://tailwindcss.com/blog/tailwindcss-v3-3#esm-and-typescript-support)! 🥳🎉
> chore: update `tailwindcss` version

- remix.config.js
See https://github.com/remix-run/indie-stack/actions/runs/4854502641/jobs/8652017500#step:6:116
> chore: silence V2 warnings

- cypress/tsconfig.json
- https://github.com/cypress-io/cypress/issues/26930#issuecomment-1602799361
- https://docs.cypress.io/guides/tooling/typescript-support#Configure-tsconfigjson
> fix: fix Cypress typecheck

- mocks/index.js
> fix: fix dev server mocks

- Dockerfile
This should have been in #257 🙈
> fix: update Node version in `Dockerfile`

- fly.toml
- start.sh
> feat: set swapfile size in `fly.toml`
